### ISSUE TITLE
Game Recorder & Playback

### ISSUE THREAD

**Issue by alwaysbusy** [SEPRFVS/FVS4#4]
Replay mode: add a replay mode to the game, such that a selected set of turns can be recorded and then ‘replayed’ quickly (e.g., similar to the record-and-playback mode supported in some racing games). It should be possible to watch the ‘replay’ in faster-than-real-time (so, for example, a set of turns that originally took 20 minutes to play will take much less than 20 minutes to watch in a replay!)
- Replay at faster speed
- Replay game that has ended
- jump to playback during gameplay
- See if it's feasible to jump to any turn during playback

@alwaysbusy will be recoving the screen recorder code

**Comment by alwaysbusy** [comment]
FVS2/commit/11a9e3e

**Comment by Juddling** [comment]
Screenshots are coming out at around 700kb on my machine.

This would mean un-optimised, running at 10 fps (which would probably look fine), we're talking... ~ 4GB for 10 mins of footage.

**Comment by Juddling** [comment]
- needs to actually perform clicks
- click turns need to be stored
- non-deterministic featues (resources and goals) potentially store the seed? storing the seed would work... http://stackoverflow.com/questions/12458383/java-random-numbers-using-a-seed

**Comment by Juddling** [comment]
Can't find a way to pragmatically click at x,y so I can use this to get an actor and manually set it to clicked()

http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/Stage.html#hit-float-float-boolean-

**Comment by Juddling** [comment]
To Do:
- ~~not getting clicks from dialog buttons~~
- ~~messed up formatting on LHS buttons~~
- ~~losing subclass functionality of classes which extend click listener (all ClickListener() should instead be ReplayClickListener()) ... reason tooltips for stations are gone~~
- ~~be able to replay clicks from dialog buttons~~
- ~~all dialogs must extend replay dialog~~
- ~~dialog not closing after PLACE action is replayed~~
- ~~route complete / cancel buttons aren't being logged~~
- ~~goal button clicks must be logged (because goals can be dropped)~~
- ~~fixed owen's actor not found bug, down to tooltips spawn another actors so unique names of game vs replay were not the same~~
- ~~BUG: skip resource dialog not showing~~
- BUG: multiple trains at one station
- FEATURE: button to play back clicks at different intervals, (100ms, 250ms, 500ms, 1s, 2s) make sure clicks aren't performed while game is animating

**Comment by Juddling** [comment]
Notes for report:
- Superclass of all Dialogs (except end game dialog) added
- New screen extending functionality of gamescreen added
- globally catching co-ordinates of all clicks was possible but did not work in practise
- Stage class extended for naming actors, only use special method for naming actors if we're interested in when they're clicked for the replay
- use of ReplayClickListener make sure all existing listeners call super.clicked()

**Comment by alwaysbusy** [comment]
Click listener found in actor
playing single...21
Exception in thread "LWJGL Application" java.lang.RuntimeException: Actor 1080 not found
    at gameLogic.replay.ReplayManager.clickActorInStage(ReplayManager.java:89)
    at gameLogic.replay.ReplayManager.playSingle(ReplayManager.java:61)
    at fvs.taxe.GameScreen.render(GameScreen.java:180)
    at com.badlogic.gdx.Game.render(Game.java:46)
    at fvs.taxe.TaxeGame.render(TaxeGame.java:55)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:214)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

This has happened multiple times whilst routing trains when it should be clicking the Confirm Route button (I think it's because a new Confirm Route button is generated each time to handle the whole view route system)

**Comment by alwaysbusy** [comment]
In UIRedesign/Dev a UnifiedDiaog has been introduced which will cause issues with ReplayDialog as it uses a different constructor.  I'll try to fix by merging to UIRedesign.

**Comment by alwaysbusy** [comment]
Tooltips don't show when hovering over a stations or junctions
